// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5KtyUAHaYe_zy726pawF48Kv_dXCH81Q',
    appId: '1:982703391602:web:d295ff50c260b6fb2453eb',
    messagingSenderId: '982703391602',
    projectId: 'aromas-fashion',
    authDomain: 'aromas-fashion.firebaseapp.com',
    storageBucket: 'aromas-fashion.firebasestorage.app',
    measurementId: 'G-YCZF26VYKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7dBFmMnQeD-mqLYnvI5us4oTglqQALs4',
    appId: '1:982703391602:android:d825df4e796e1b672453eb',
    messagingSenderId: '982703391602',
    projectId: 'aromas-fashion',
    storageBucket: 'aromas-fashion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfWGSNnc435s4xTrVxESI_QcuZVu1NQhc',
    appId: '1:982703391602:ios:be552588d1ebf3ea2453eb',
    messagingSenderId: '982703391602',
    projectId: 'aromas-fashion',
    storageBucket: 'aromas-fashion.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfWGSNnc435s4xTrVxESI_QcuZVu1NQhc',
    appId: '1:982703391602:ios:be552588d1ebf3ea2453eb',
    messagingSenderId: '982703391602',
    projectId: 'aromas-fashion',
    storageBucket: 'aromas-fashion.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5KtyUAHaYe_zy726pawF48Kv_dXCH81Q',
    appId: '1:982703391602:web:166d1c34ffe5fd712453eb',
    messagingSenderId: '982703391602',
    projectId: 'aromas-fashion',
    authDomain: 'aromas-fashion.firebaseapp.com',
    storageBucket: 'aromas-fashion.firebasestorage.app',
    measurementId: 'G-QPHCF6Q3PE',
  );
}
